### PR TITLE
Added reaction-timer uwp project under_site/demo/uwp

### PR DESCRIPTION
**Pull request by amoraitis**
UWP section
Added a reaction timer uwp
Here the gif demo:

reactiondemovideo

Let me know if you want a small how to

### CODE REVIEW

**Comment by shamdasani** [comment]
Thanks! It would be awesome if you could write a tutorial so that users know how to recreate it!

**Comment by amoraitis** [comment]
@samayshamdasani Please review my GettingStarted file!

**Comment by shamdasani** [comment]
Looks good, but do you mind submitting another pull request that's in the root demo file - and not the one under _site? _site has just the compiled static files and it gets overwritten...

**Comment by amoraitis** [comment]
Ok i think its ok now!

**Pull request closed without merging**
